server:
  port: 8085


spring:
  datasource:
    url: jdbc:h2:mem:sample-app;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    platform: h2
    username: sa
    password:
    driverClassName: org.h2.Driver

  session:
    timeout : 10s

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true

  h2:
    console:
      enabled: true
      path: /console
      settings:
        trace: false
        web-allow-others: false

application:
  client :
    url : http://192.168.43.153:8085
    feature :
      getLogin : /client/
  compte :
    url : http://192.168.43.160:8085
    feature :
      withdraw: /account/transaction
      getIdAccount: /account/getIdCustomer

  mail :
    url: http://192.168.43.220:8085
    feature:
      send : /mailing/send
  facture :
    url: http://192.168.43.161:8085
    feature:
      create: /facture/create
  securite :
    url: http://192.168.43.244:8085
    feature:
      check : /user/
      service : /rights/transaction
  monetique :
    url: http://192.168.43.231:8095
    feature:
      getCards : /GetIdCb
      check : /monetique/
      service : /pay